GET http://localhost:5000/api/

########################################## DEVICES
GET http://localhost:5000/api/devices

### insert device
POST http://localhost:5000/api/devices
Content-Type: application/json

{
    "deviceType": "Laptop",
    "model": "Lenovo T15",
    "serialNumber": "AB0789788",
    "inventoryNumber": 8001,
    "status": "Available"
}

### update device data
PUT http://localhost:5000/api/devices/1
Content-Type: application/json

{
    "deviceType": "Laptop",
    "model": "Lenovo T15",
    "serialNumber": "AB098089",
    "inventoryNumber": 8000,
    "status": "Unavailable"
}

### delete device
DELETE http://localhost:5000/api/devices/2

############################################# USERS
GET http://localhost:5000/api/users

############################################# HISTORY
GET http://localhost:5000/api/history

