GET http://localhost:5000/api/

########################################## DEVICES
GET http://localhost:5000/api/devices

### insert device
POST http://localhost:5000/api/devices
Content-Type: application/json

{
    "deviceType": "Laptop",
    "model": "Lenovo T15",
    "serialNumber": "AB0789788",
    "inventoryNumber": 8001,
    "status": "Available"
}

### update device data
PUT http://localhost:5000/api/devices/1
Content-Type: application/json

{
    "deviceType": "Laptop",
    "model": "Lenovo T15",
    "serialNumber": "AB098089",
    "inventoryNumber": 8000,
    "status": "Unavailable"
}

### delete device
DELETE http://localhost:5000/api/devices/2

############################################# USERS
GET http://localhost:5000/api/users

### insert user
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "fullName": "Test User",
    "role": "user",
    "username": "testuser2",
    "password": "testuser",
    "email": "test2@user.com"
}

### delete user
DELETE http://localhost:5000/api/users/1

### edit user
PUT http://localhost:5000/api/users/4
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@user.com"
}

############################################# HISTORY
GET http://localhost:5000/api/history

### insert data into history
POST http://localhost:5000/api/history
Content-Type: application/json

{
    "userId": "4",
    "deviceId": "1",
    "rentDate": "2025-01-18",
    "returnDate": "2025-01-21"
}

### delete data from history
DELETE http://localhost:5000/api/history/1